[package]
name = "rs-csv-validator"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }
csv = "1.3.1"
jsonschema = "0.30.0"
serde = "1.0.219"
serde_json = "1.0.140"
